apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts.sockshop-baseline-production.svc.cluster.local
  - carts
  http:
  - route:
    - destination:
        host: carts-canary.sockshop-baseline-production.svc.cluster.local
    - destination:
        host: carts-primary.sockshop-baseline-production.svc.cluster.local
      weight: 100
